version: "3"
services:
  scylladb:
    image: scylladb/scylla:3.0.3
    ports:
      - "7000-7001:7000-7001"
      - "9042:9042"
      - "9160:9160"
      - "10000:10000"
      - "7199:7199"
    volumes:
      - "./scylla-rdf-data/scylla:/var/lib/scylla"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - "./scylla-rdf-data/elasticsearch:/usr/share/elasticsearch/data"
  scylla-rdf:
    build: ./
    image: datafabricrus/scylla-rdf:0.0.1
    depends_on:
      - scylladb
      - elasticsearch
    ports:
      - "80:80"
    volumes:
      - "./scylla-rdf-data/rdf4j:/root/.RDF4J"

