version: "3"
services:
  scylladb:
    image: scylladb/scylla:3.0.3
    ports:
      - "7000-7001:7000-7001"
      - "9042:9042"
      - "9160:9160"
      - "10000:10000"
      - "7199:7199"
  scylla-rdf:
    build: ./
    image: datafabricrus/scylla-rdf:0.0.1
    volumes:
      - "./rdf4j-conf:/root/.RDF4J"
    ports:
      - "80:80"

